name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    get-temp-token:
      runs-on: ubuntu-latest

      steps:
        - name: Get Token
          id: get_workflow_token
          uses: peter-murray/workflow-application-token-action@v3
          with:
            application_id: ${{ secrets.APPLICATION_ID }}
            application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

        - name: Use Application Token to create a release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          with:
            release_name: '0.0.1'
            tag_name: '0.0.1'

    build:
        runs-on: ubuntu-latest

        permissions:
          pull-requests: write

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            distribution: 'adopt'
            java-version: '21'

        - name: Build with Maven
          run: mvn clean install

        - name: Test with Maven
          run: mvn test

        - uses: LouisBrunner/checks-action@v2.0.0
          if: always()
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            name: Test Maven
            conclusion: ${{ job.status }}
            output: |
              {"summary":"${{ steps.test.outputs.summary }}"}
